name: "framework testing action"

on: [push]

jobs:
  test-the-framework:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
    - run: php ./vendor/bin/phpcs --standard=PSR12 src tests
    - run: php ./vendor/bin/phpstan analyse src tests --level 7
    - run: php ./vendor/bin/phpunit tests
